name: random_Fun
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 4.0.0+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^1.1.0
  font_awesome_flutter: ^8.8.1
  google_sign_in: ^4.4.6
  firebase_auth: ^0.16.0
  provider: ^4.1.1
  modal_progress_hud: ^0.1.3
  flip_card: ^0.4.4
  http: ^0.12.1
  fluttertoast: ^4.0.1
  cloud_firestore: ^0.13.5
  image_picker: ^0.6.6+1
  firebase_storage: ^3.1.5
  curved_navigation_bar: ^0.3.2
  chips_choice: ^1.2.0
  cached_network_image: ^2.2.0+1
  draggable_scrollbar_sliver: ^0.0.3
  time_formatter: ^1.0.0+5
  shared_preferences: ^0.5.7+3
  firebase_messaging: ^6.0.16
  flutter_overboard: ^1.1.5
  firebase_admob: ^0.9.3+2
  flare_splash_screen: ^3.0.1
  flare_loading: ^2.1.1
  simple_animations: ^2.2.1
  page_transition: ^1.1.5
  url_launcher: ^5.4.10
  
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  intl: ^0.16.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.5


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/flares/animation.flr


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: ProductSans
      fonts:
        - asset: assets/fonts/ProductSans-Medium.ttf
    - family: Aileron
      fonts:
        - asset: assets/fonts/Aileron-SemiBold.otf
        #   style: italic
        # - asset: assets/fonts/Aileron-Italic.otf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
